"use client"
import { Origami, Globe2Icon, LayoutDashboard, Loader2, X } from "lucide-react"
import Image from "next/image"
import { Button } from "@/components/ui/button"
import { useState, useEffect } from "react"
import { ArrowRight, Link } from "lucide-react"
import { useRouter } from "next/navigation"
import { copyTemplateToUser, getAllWebsiteTemplates } from "@/lib/website-actions"
import { motion, AnimatePresence } from "framer-motion"
import mat from "@/asset/mat.gif";
import { description } from "@/components/chart"
import { Textarea } from "@/components/ui/textarea"
import { DraftView} from "@/components/modal"







interface PageProps {
  params: Promise<{
    username: string
  }>
}

// Template data
const templates = [
  {
    id: "1",
    imageSrc:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/MDczMjE0NTNhYWVkN2Q0ODAyZWUxY2Q4YjQxMzY4MjI.jpg-RtJL8JHAO7YC1XcO6N0JhCHjpTWhNC.jpeg",
    title: "Blank Canvas",
    description: "Your HTML5 sandbox—tinker with code generated by ChatGPT, or generate a full website with our AI"
  },
  {
    id: "2",
    imageSrc: "https://i.postimg.cc/RVJmVNHh/MDcz-Mj-E0-NTNh-YWVk-N2-Q0-ODAy-ZWUx-Y2-Q4-Yj-Qx-Mz-Y4-Mj-I.jpg",
    title: "Silent Ink",
    description: "Calligraphic, minimal, white background, no images, and looks like an elegant business card"
  },
  {
    id: "3",
    imageSrc: "https://49iw5aq3b5e3nyxk.public.blob.vercel-storage.com/11234",
    title: "Peekaboo",
    description: "Ultra-low content, perfectly suited for a subtle, stylish link-in-bio. Open, explore… or don’t"

  },
  {
    id: "4",
    imageSrc: "https://49iw5aq3b5e3nyxk.public.blob.vercel-storage.com/heloaos",
    title: "Kenny?",
    description: "Full of personality, multi-section with 2D animations, for B2C brands. Totally clickable"
  },

  {
    id: "5",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%201-uSx6JzCKD5Kmmg9IDbAnNl7OHnAk8b.png",
    title: "Stokebury",
    description: "Ultra-professional layout, with image-driven sections. For agencies and solo creators."
  },
   {
    id: "6",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%201-79YVrd7eG22eykmzjTZyAq7YKcuug3.png",
    title: "Slot-Machine",
    description: "3D scrolling animation that shouts out for business—one word at a time. Perfect for Risk-Takers"
  },
   {
    id: "7",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%202-7EhoFLYBDcTrCE6L5oSI8c6UEP3NFo.png",
    title: "Relaxof",
  },
   {
    id: "8",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%202-7EhoFLYBDcTrCE6L5oSI8c6UEP3NFo.png",
    title: "Relaxof",
  },
    {
    id: "9",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%202-7EhoFLYBDcTrCE6L5oSI8c6UEP3NFo.png",
    title: "Relaxof",
  },
    {
    id: "10",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%202-7EhoFLYBDcTrCE6L5oSI8c6UEP3NFo.png",
    title: "Relaxof",
  },
    {
    id: "11",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%202-7EhoFLYBDcTrCE6L5oSI8c6UEP3NFo.png",
    title: "Relaxof",
  },

   {
    id: "12",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%202-7EhoFLYBDcTrCE6L5oSI8c6UEP3NFo.png",
    title: "Relaxof",
  },
   {
    id: "13",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%202-7EhoFLYBDcTrCE6L5oSI8c6UEP3NFo.png",
    title: "Corporate Skycraper",
  },
    {
    id: "14",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%202-7EhoFLYBDcTrCE6L5oSI8c6UEP3NFo.png",
    title: "Corporate Skycraper",
  },
   {
    id: "15",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%202-7EhoFLYBDcTrCE6L5oSI8c6UEP3NFo.png",
    title: "Booking",
  },
  {
    id: "16",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%202-7EhoFLYBDcTrCE6L5oSI8c6UEP3NFo.png",
    title: "k-pop",
  },
  {
    id: "17",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%202-7EhoFLYBDcTrCE6L5oSI8c6UEP3NFo.png",
    title: "my bio",
  },
  {
    id: "18",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%202-7EhoFLYBDcTrCE6L5oSI8c6UEP3NFo.png",
    title: "my bio",
  },
   {
    id: "19",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%202-7EhoFLYBDcTrCE6L5oSI8c6UEP3NFo.png",
    title: "my bio",
  },
   {
    id: "20",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%202-7EhoFLYBDcTrCE6L5oSI8c6UEP3NFo.png",
    title: "my bio",
  },
   {
    id: "21",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%202-7EhoFLYBDcTrCE6L5oSI8c6UEP3NFo.png",
    title: "my bio",
  },
   {
    id: "22",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%202-7EhoFLYBDcTrCE6L5oSI8c6UEP3NFo.png",
    title: "my bio",
  },
   {
    id: "23",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%202-7EhoFLYBDcTrCE6L5oSI8c6UEP3NFo.png",
    title: "my bio",
  },
  {
    id: "24",
    imageSrc: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Artboard%202-7EhoFLYBDcTrCE6L5oSI8c6UEP3NFo.png",
    title: "my bio",
  },
]

export default function Page({ params }: PageProps) {
  const username = "aftlatuun"
  const router = useRouter()
  const [isNavigating, setIsNavigating] = useState(false)
  const [selectedTemplateId, setSelectedTemplateId] = useState<string | null>(null)
  const [showPreviewModal, setShowPreviewModal] = useState(false)
  const [showConfirmModal, setShowConfirmModal] = useState(false)
  const [previewTemplateId, setPreviewTemplateId] = useState<string | null>(null)
  const [templateData, setTemplateData] = useState<any>(null)
  const [isLoadingTemplate, setIsLoadingTemplate] = useState(false)
  const [allTemplateData, setAllTemplateData] = useState<any[]>([])
  const [isLoadingAllTemplates, setIsLoadingAllTemplates] = useState(true)
    
  

  const createCombinedHtml = (templateData: any) => {
    if (!templateData || templateData.length === 0) return ""

    const data = templateData[0]
    let combinedHtml = data.code || ""

    // Ensure data.js is loaded before script.js
    // Replace <script src="data.js"></script> with inline data
    if (data.code_data) {
      combinedHtml = combinedHtml.replace('<script src="data.js"></script>', `<script>\n${data.code_data}\n</script>`)
    }

    // Replace <script src="script.js"></script> with inline script
    if (data.code_script) {
      combinedHtml = combinedHtml.replace(
        '<script src="script.js"></script>',
        `<script type="text/babel">\n${data.code_script}\n</script>`,
      )
    }

    return combinedHtml
  }


  useEffect(() => {
    const fetchAllTemplates = async () => {
      try {
        console.log("[v0] Fetching all templates on page load")
        const data = await getAllWebsiteTemplates()
        setAllTemplateData(data)
        console.log("[v0] All templates cached:", data.length)
      } catch (error) {
        console.error("Failed to fetch all templates:", error)
      } finally {
        setIsLoadingAllTemplates(false)
      }
    }

    fetchAllTemplates()
  }, [])




 const handlePreviewTemplate = async (templateId: string) => {
  if (isLoadingAllTemplates || !allTemplateData || allTemplateData.length === 0) {
    alert("Templates are still loading. Please wait a moment.");
    return;
  }

  setPreviewTemplateId(templateId);
  setShowPreviewModal(true);

  const foundTemplate = allTemplateData.find(
    (template) => template.id === Number(templateId)
  );

  if (!foundTemplate) {
    console.error("Template not found in cached data:", templateId);
    alert("Template not found. Please refresh the page.");
    setShowPreviewModal(false);
    return;
  }

  // ✅ Set template data for the iframe
  setTemplateData([foundTemplate]);
};



   const getCurrentTemplateData = () => {
    if (!previewTemplateId) return null
    return allTemplateData.find((template) => template.id === Number(previewTemplateId))
  }
  

  const handleSelectTemplate = async (templateId: string) => {
    setIsNavigating(true)
    setSelectedTemplateId(templateId)

    await new Promise((resolve) => setTimeout(resolve, 300))
    try {
      const result = await copyTemplateToUser(Number(templateId), username)

      if (result?.success) {
        router.push(`/edit/${username}`)
      } else {
        alert(`⚠️ Failed to copy template: ${result?.error || "Unknown error"}`)
        setIsNavigating(false)
        setSelectedTemplateId(null)
      }
    } catch (error) {
      console.error("Failed to copy template:", error)
      alert("⚠️ Failed to copy template. Please try again.")
      setIsNavigating(false)
      setSelectedTemplateId(null)
    }
  }

  const handleConfirmEdit = () => {
    setShowConfirmModal(false)
    setShowPreviewModal(false)
    if (previewTemplateId) {
      handleSelectTemplate(previewTemplateId)
    }
  }

 useEffect(() => {
  if (showPreviewModal) {
    document.body.style.overflow = "hidden"; // disable page scroll
  } else {
    document.body.style.overflow = "auto"; // restore scroll
  }
}, [showPreviewModal]);


 

function TemplateList() {
  return (
    <section className="py-16 px-4 bg-black" style={{ zoom: 0.95 }}>
      <div className="max-w-screen-xl mx-auto p-5 sm:p-10 md:p-16">

        {/* Header */}
       <div className={`border-b border-stone-800 mb-12 flex justify-between items-center text-sm 
     sticky top-0 z-10 bg-black/50 backdrop-blur-sm ${showPreviewModal ? "hidden" : "z-30"}`}>

  {/* Left - Title */}
  <div className="text-white flex items-center pb-1 pr-4 border-b-2 border-white uppercase tracking-wide">
    <svg className="h-6 mr-3" viewBox="0 0 455.005 455.005">
      <path d="M446.158,267.615c-5.622..."></path>
    </svg>
    <span className="font-semibold inline-block">All Templates</span>
  </div>

  {/* Right Tabs */}
  <div className="flex gap-6 text-white">
    {["Founder", "Creator", "Job Seeker", "SaaS", "FanPage", "E-Commerce", "Coach"].map((tab) => (
      <button
        key={tab}
        className="hover:text-white transition pb-1  mt-2 border-b-2 border-transparent hover:border-indigo-500"
      >
        {tab}
      </button>
    ))}
  </div>

</div>


        {/* Cards */}
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-14 px-2">
          {templates.map((template, index) => (
            <motion.div
              key={template.id}
              initial={{ opacity: 0, y: 80 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1, duration: 0.3 }}
              className="rounded-xl overflow-hidden shadow-lg flex flex-col bg-stone-900 border border-stone-800 hover:border-stone-700 transition"
            >
              {/* Image */}
              <div className="relative">
                <img
                  src={template.imageSrc}
                  alt={template.title}
                  className="w-full h-52 object-cover"
                />
              </div>

              {/* Content */}
              <div className="px-7 py-5 mb-auto">
                <h3 className="font-medium text-lg text-white hover:text-indigo-500 transition mb-2">
                  {template.title}
                </h3>

                <p className="text-gray-400 text-sm leading-relaxed">
                  {template.description ??
                    "This is a short description for the template."}
                </p>
              </div>

              {/* Footer */}
              <div className="px-7 py-4 flex items-center justify-between bg-stone-800/70 backdrop-blur-sm">

                {/* Time */}
                <span className="py-1 text-xs text-gray-300 flex items-center">
                  <svg height="14" width="14" viewBox="0 0 512 512">
                    <path fill="white" d="M256,0C114.8..."></path>
                  </svg>
                  <span className="ml-1">FREE</span>
                </span>

                {/* Glass Preview Button */}
                <button
                  onClick={() => handlePreviewTemplate(template.id)}
                  className="
                    relative inline-flex items-center justify-center 
                    px-4 py-2 text-white text-xs rounded-lg 
                    bg-white/5 border border-white/30 backdrop-blur-sm 
                    shadow-[inset_0_1px_0px_rgba(255,255,255,0.6),0_0_8px_rgba(0,0,0,0.2),0_3px_6px_rgba(0,0,0,0.15)]
                    hover:bg-white/20 
                    transition-all duration-300 
                    before:absolute before:inset-0 before:rounded-lg 
                    before:bg-gradient-to-br before:from-white/50 before:via-transparent 
                    before:to-transparent before:opacity-70 before:pointer-events-none
                    after:absolute after:inset-0 after:rounded-lg 
                    after:bg-gradient-to-tl after:from-white/20 after:via-transparent 
                    after:to-transparent after:opacity-40 after:pointer-events-none
                    antialiased
                  "
                >
                  Preview
                </button>

              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}


  function PreviewModal() {
  if (!showPreviewModal) return null;
  const currentTemplateData = getCurrentTemplateData();
      const [isDraftOpen, setIsDraftOpen] = useState(false)

  

  return (<>
    <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-lg flex items-center justify-center">

      {/* Outer Container */}
      <div className="bg-[#101012] rounded-2xl w-full h-full max-w-screen-2xl shadow-2xl border border-white/10 flex flex-col overflow-hidden">

        {/* Top Bar */}
        <div
          style={{ zoom: 0.85 }}
          className="flex items-center justify-between px-8 py-4 
          bg-[#18181B]/80 backdrop-blur-md border-b border-white/10"
        >

          {/* Window buttons */}
          <div className="flex items-center gap-2">
            <span className="w-3 h-3 bg-red-500 rounded-full shadow-sm"></span>
            <span className="w-3 h-3 bg-yellow-400 rounded-full shadow-sm"></span>
            <span className="w-3 h-3 bg-green-500 rounded-full shadow-sm"></span>
          </div>

          
            


          {/* Actions */}
          <div className="flex items-center gap-4">

            {/* Close */}
               <button
            type="button"
            onClick={() => setIsDraftOpen(true)}
            className="text-stone-300 flex items-center "
          >Full View
          </button>
            <button
              onClick={() => setShowPreviewModal(false)}
              className="p-2 rounded-lg hover:bg-white/10 transition text-white"
            >
              <X className="w-4 h-4" />
            </button>

            {/* Make It Yours */}
            <button
              onClick={() => setShowConfirmModal(true)}
              disabled={!currentTemplateData}
              className="
                relative inline-flex items-center justify-center gap-2
                px-4 py-2 text-sm font-medium text-white rounded-lg
                bg-white/5 border border-white/20 backdrop-blur-md
                shadow-[inset_0_1px_0px_rgba(255,255,255,0.4),0_0_8px_rgba(0,0,0,0.3),0_3px_8px_rgba(0,0,0,0.25)]
                hover:bg-white/15 transition-all duration-300
                before:absolute before:inset-0 before:rounded-lg 
                before:bg-gradient-to-br before:from-white/50 before:via-transparent 
                before:to-transparent before:opacity-60 before:pointer-events-none
                disabled:opacity-40 disabled:cursor-not-allowed
              "
            >
              Make It Yours
              <ArrowRight className="w-4 h-4" />
            </button>

          </div>
        </div>

        {/* Content Area */}
        <div className="flex-1 px-8 py-2 overflow-hidden" style={{ zoom: 0.8 }}>
          {isLoadingTemplate ? (
            <div className="flex items-center justify-center h-full text-white/90">
              <Loader2 className="w-6 h-6 animate-spin" />
              <span className="ml-2 text-sm">Loading template preview...</span>
            </div>
          ) : templateData ? (
            <motion.div
              key={previewTemplateId}
              initial={{ opacity: 0, scale: 0.96, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.96, y: 20 }}
              transition={{ duration: 0.35, ease: "easeOut" }}
              className="w-full h-full"
            >
              <iframe
                srcDoc={createCombinedHtml(templateData)}
                className="w-full h-full border-0 rounded-xl bg-white shadow-lg"
                title="Template Preview"
                sandbox="allow-scripts allow-same-origin"
              />
            </motion.div>
          ) : (
            <div className="flex items-center justify-center h-full text-white/70">
              No template data available
            </div>
          )}
        </div>
      </div>
    </div>

    
             <DraftView
            isOpen={isDraftOpen}
            onClose={() => setIsDraftOpen(false)}
            debouncedContent={createCombinedHtml(templateData)}
          /></>
  );
}

function ConfirmModal() {
  if (!showConfirmModal) return null;

  return (
    <AnimatePresence>
      <motion.div
        className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xl flex items-center justify-center p-4"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        transition={{ duration: 0.3, ease: "easeInOut" }}
      >
        <motion.div
          className="relative bg-white/90 backdrop-blur-md rounded-3xl p-8 max-w-md w-full shadow-2xl border border-gray-100"
          initial={{ opacity: 0, scale: 0.85, y: 30 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.85, y: 30 }}
          transition={{
            type: "spring",
            stiffness: 180,
            damping: 16,
            mass: 0.9
          }}
        >
          {/* ❌ Close Icon */}
          <button
            onClick={() => setShowConfirmModal(false)}
            className="absolute top-4 right-4 text-gray-500 hover:text-gray-700 transition"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={2}
              stroke="currentColor"
              className="w-5 h-5"
            >
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>

          {/* Title */}
          <h3 className="text-gray-900 text-2xl font-bold mb-3 text-center">
            Go ahead?
          </h3>

          {/* Description */}
          <p className="text-gray-600 mb-6 text-center leading-relaxed">
            When copied, the template opens for editing.  
            Your old site will no longer stay active.
          </p>

          {/* Textarea */}
          <div className="mb-6">
            <textarea
             
              placeholder="Ask anything..."
              className="px-4 py-3 pb-12 w-full text-gray-900 text-sm 
                         bg-black/10 border border-black/20 backdrop-blur-sm 
                         rounded-lg shadow-[inset_0_1px_0px_rgba(0,0,0,0.15),0_3px_8px_rgba(0,0,0,0.1)]
                         placeholder:text-gray-500 
                         focus:bg-white/50 focus:outline-none focus:ring-2 focus:ring-black/20
                         transition-all duration-300 resize-none"
            ></textarea>
          </div>

          {/* Action Buttons */}
          <div className="flex items-center justify-center gap-3">

            {/* Let’s Go */}
            <Button
              onClick={handleConfirmEdit}
              className="px-6 py-2 rounded-lg bg-black text-white hover:bg-gray-900 shadow-md hover:shadow-lg transition"
            >
              Let’s Go
            </Button>

            {/* Skip (same behavior) */}
            <Button
              onClick={handleConfirmEdit}
              className="px-6 py-2 rounded-lg bg-gray-200 text-gray-700 hover:bg-gray-300 shadow transition"
            >
              Skip
            </Button>

          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}



  return (
    <div className="bg-[#030712] min-h-screen text-white">
     {isNavigating && (
      <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center">
        <div className="bg-white/10 backdrop-blur-md   flex flex-col items-center ">
          {/* Show GIF from public folder */}
          <Image src={mat} alt="Loading animation" width={164} height={164} />


          {/* Spinner + text */}
          <div className="flex items-center">
            <span className="text-white font-medium mb-3 -mt-4">Loading Editor..</span>
          </div>
        </div>
      </div>
    )}

      <div className="flex">
        {/* Left Sidebar */}
       

        {/* Main Content */}
        <main className="flex flex-1 items-center justify-center px-4 py-16" style={{ zoom: 0.8 }}>
          <div className="text-center max-w-5xl w-full">
            <h1 className="text-white text-5xl md:text-7xl lg:text-8xl font-extrabold tracking-tight leading-tight">
             founders launch a website in minutes!
            </h1>
            <p className="mt-8 text-lg md:text-xl text-white font-extrabold leading-relaxed max-w-4xl mx-auto">
            Stop fantasizing. Start validating. Just tell us what you do, and our AI creates a clear, professional site that speaks to your audience.  Sometimes a single visitor is all it takes. One person can enbrace your idea and reimagine their life — and yours too.


            </p>
          </div>
        </main>
      </div>

      {/* Template List Section */}
      <TemplateList />

      <PreviewModal />
      <ConfirmModal />
    </div>
  )
}
